variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository   # place storage for cache

image: maven:3.8.7-eclipse-temurin-19

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - package
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - prod

  script:
    - echo "Maven build started"

test-job:       # This job runs in the test stage, which runs second .
  stage: test
  tags:
    - prod

  script:
    - echo "Maven test started"

package-job:       # This job runs in the package stage, which runs third.
  stage: package
  tags:
    - prod

  script:
    - echo "Maven packaging started"


deploy_dev_server:  # This job runs in the deploy stage, which runs fourth.
  stage: deploy
  tags:
    - prod

  before_script:
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y ) # which ищет исполняемый файл
    #|| если выполнение первой команды статус 1 (не удачно), то переход ко второй.
    #update - Обновление базы данных пакетов. install - устанавливает пакет openssh-client
    - eval $(ssh-agent -s) #типо execute immediate запускает ssh_agent в дочернем процессе от оболочки
    - echo ssh-rsa "${SSH_PRIVATE_KEY}"  | ssh-add -
  script:
    -echo "empty"