stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

Docker build:
  stage: build
  script:
    - echo 'docker build is successfull'
  tags:
    - prod

Unit tests:
  stage: test
  script:
    - echo 'this is unit test!'

Deploy to Dev:
  stage: deploy
  script:
    - echo '${(}CI_PROJECT_NAME} from branch ${CI_COMMIT_REF_SLUG}' [#${CI_COMMIT_SHORT_SHA}]>> ~/build.txt
  tags:
    - prod
