variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

image: maven:3.8.7-amazoncorretto-19

stages:          # List of stages for jobs, and their order of execution
  - build
  - package

cache:
  paths:
    - .m2/repository
    - target

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - prod

  script:
    - echo "Compiling the code..."
    - "mvn compile"

package-job:       # This job runs in the build stage, which runs first.
  stage: package
  tags:
    - prod

  script:
    - echo "Maven packaging started"
    - "mvn package -Dmaven.test.skip"