variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

image: maven:latest

stages:          # List of stages for jobs, and their order of execution
  - build

cache:
  paths:
    - .m2/repository
    - target

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - prod
  script:
    - echo "Compiling the code..."
    - "mvn compile"