variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

image: maven:3.8.7-amazoncorretto-19

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - package
  - deploy

cache:
  paths:
    - .m2/repository
    - target

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - prod

  script:
    - echo "Compiling the code..."
    - "mvn compile"

test-job:       # This job runs in the test stage, which runs second.
  stage: test
  tags:
    - prod

  script:
    - echo "Maven test started"
    - "mvn test -Dmaven.test.skip"

package-job:       # This job runs in the package stage, which runs third.
  stage: package
  tags:
    - prod

  script:
    - echo "Maven packaging started"
    - "mvn package -Dmaven.test.skip"

deploy-job:       # This job runs in the deploy stage, which runs fourth.
  stage: deploy
  tags:
    - prod

  script:
    - echo "Maven deploy started"