variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository   # place storage for cache

image: maven:3.8.7-amazoncorretto-19

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - package
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - prod

  script:
    - echo "Compiling the code..."
    - "mvn compile"

  cache:
    paths:
      - .m2/repository
      - target

test-job:       # This job runs in the test stage, which runs second.
  stage: test
  tags:
    - prod

  script:
    - echo "Maven test started"
    - "mvn test -Dmaven.test.skip"

  cache:
    paths:
      - .m2/repository
      - target

package-job:       # This job runs in the package stage, which runs third.
  stage: package
  tags:
    - prod

  script:
    - echo "Maven packaging started"
    - "mvn package -Dmaven.test.skip"

  artifacts:
    paths:
      - target/*.jar
  cache:
    policy: pull
    paths:
      - .m2/repository
      - target


deploy-job:       # This job runs in the deploy stage, which runs fourth.
  stage: deploy
  tags:
    - prod

  script:
    - echo "Maven deploy started"