variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository   # place storage for cache

image: maven:3.8.7-eclipse-temurin-19

stages:          # List of stages for jobs, and their order of execution 
  - build
  - test
  - sonarqube
  - package
  - deploy

build-job:       # This job runs in the build stage, which runs first. 
  stage: build
  tags:
    - students

  script:
    - echo "Compiling the code $CI_JOB_STAGE... $DEV_USER"
    - "mvn compile"

  cache:
    paths:
      - .m2/repository
      - target

test-job:       # This job runs in the test stage, which runs second.
  stage: test
  tags:
    - students

  script:
    - echo "Maven test started"
    - "mvn test"

  cache:
    paths:
      - .m2/repository
      - target
sonarqube-check:
    stage:
        sonarqube
    tags:
      - students
    variables:
        SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
        GIT_DEPTH: "0"
    cache:
        paths:
            - .sonar/cache
    script:
        -  mvn verify sonar:sonar -Dsonar.projectKey=javapro_team34_zerone_backend_AYcJWhGuf3krGjKJWJH6 -Dsonar.login=admin -Dsonar.password=admin1
    allow_failure: true

package-job:       # This job runs in the package stage, which runs third.
  stage: package
  tags:
    - students

  only:
    - master

  script:
    - echo "Maven packaging started"
    - "mvn package -Dmaven.test.skip"

  artifacts:
    paths:
      - target/*.jar
  cache:
    policy: pull
    paths:
      - .m2/repository
      - target


deploy_dev_server:  # This job runs in the deploy stage, which runs fourth.
  stage: deploy
  tags:
    - students

  only:
    - master

  before_script:
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y ) # which ищет исполняемый файл
    #|| если выполнение первой команды статус 1 (не удачно), то переход ко второй.
    #update - Обновление базы данных пакетов. install - устанавливает пакет openssh-client
    - eval $(ssh-agent -s) #типо execute immediate запускает ssh_agent в дочернем процессе от оболочки
    - echo "$SSH_PRIVATE_KEY" | ssh-add -  # |-выходн данные первой команды передает во вторую
    #приватный ключ передаёт во вторую команду ssh-add, т.е. для авторизации в агенте
    - mkdir -p ~/.ssh #создание директории, если такой нет. -p создаст все директории, указанные в пути. Check: ls -la
    - chmod 700 ~/.ssh #выдаём права только владельцу на чтение, запись и выполнение
    - ssh-keyscan $DEV_HOST >> ~/.ssh/known_hosts #собирает ключи с хоста 195.161.62.32
    #и перенаправляет вывод в файл, но не перезаписывает его, а добавляет в конец
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - chmod 644 ~/.ssh/known_hosts #владельцу чтение, запись. Для группы и других - чтение
  script:
    - ssh $DEV_USER@$DEV_HOST "[ ! -f $DEV_APP_PATH/backend.jar ] || mv $DEV_APP_PATH/backend.jar $BACKUP/backend-build-$CI_PIPELINE_ID.jar"
    #подключ. ч/з ssh.        check path exists and он стандартный.   Перемещение файла из одной директори в другую с переименованием(бэкап)
    - scp target/zerone_backend-0.0.1-SNAPSHOT.jar $DEV_USER@$DEV_HOST:$DEV_APP_PATH/backend.jar
    - scp /builds/javapro_team34/zerone_backend/docker-compose.yaml $DEV_USER@$DEV_HOST:$USER_HOME_PATH/
    #копирование файла из репо на сервер
    - ssh $DEV_USER@$DEV_HOST "docker compose stop"
    - ssh $DEV_USER@$DEV_HOST "docker compose up -d"
