services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: skillbox
      POSTGRES_USER: skillbox
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: on-failure[5]

  frontend:
    container_name: frontend
    image: dimok82/zeone
    ports:
      - "80:80"
    restart: on-failure[5]

  backend:
    container_name: backend
    image: eclipse-temurin:19-jdk-jammy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/skillbox?stringtype=unspecified
      SPRING_DATASOURCE_USERNAME: skillbox
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_PROFILES_ACTIVE: prod
    ports:
      -  "8086:8086"
    volumes:
      - ./jars:/app
    working_dir: /app
    command: java -jar backend.jar
    depends_on: postgres
    restart: on-failure[5]

volumes:
  postgres: