version: "3.7"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.9
    container_name: zookeeper
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.9
    container_name: kafka
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  zeronekafka:
    image: grif8585yandex/zeronekafka
    container_name: zeronekafka
    working_dir: /opt
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
      KAFKA_BROKERCONNECT: "kafka:9092"
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}
    depends_on:
      - kafka
      - zookeeper

  postgres:
    container_name: postgres
    image: postgres:15.2
    environment:
      POSTGRES_DB: skillbox
      POSTGRES_USER: skillbox
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s

  redis:
    container_name: redis
    image: redis:6.2.11
    ports:
      - "6379:6379"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis:/data/redis

  frontend:
    container_name: frontend
    image: dimatch86/zerone_front_prod
    ports:
      - "80:80"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s

  backend:
    container_name: backend
    image: eclipse-temurin:19-jdk-jammy
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      -  "8088:8088"
      -  "1111:1111"
    volumes:
      - ./jars:/app
    working_dir: /app
    command: java -Djasypt.encryptor.password=${ENCRYPTION_KEY} -Ddb_password=${PG_PASSWORD} -jar backend.jar
    depends_on:
      - api-gateway
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s

  admin:
    container_name: admin
    image: eclipse-temurin:19-jdk-jammy
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8083:8083"
    volumes:
      - ./jars:/app
    working_dir: /app
    command: java -Djasypt.encryptor.password=${ENCRYPTION_KEY} -jar admin.jar
    depends_on:
      - api-gateway
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s

  eureka-server:
    container_name: eureka-server
    image: eclipse-temurin:19-jdk-jammy
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8761:8761"
    volumes:
      - ./jars:/app
    working_dir: /app
    command: java -jar eureka-server.jar
    depends_on:
      - postgres
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s

  api-gateway:
    container_name: api-gateway
    image: eclipse-temurin:19-jdk-jammy
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8086:8086"
    volumes:
      - ./jars:/app
    working_dir: /app
    command: java -jar api-gateway.jar
    depends_on:
      - eureka-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s

  grafana:
    container_name: grafana
    build: './config/grafana'
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    depends_on:
      - prometheus
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.43.0
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus:/etc/prometheus
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s

volumes:
  postgres:
  redis: