server.port: 8086

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    show-sql: true
  sql:
    init:
      mode: always
  liquibase:
    enabled: false
