server.port: 8086

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    show-sql: false
  sql:
    init:
      mode: always
  liquibase:
    enabled: false

socket-server:
  port: 1111
  host: localhost
