spring:
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/skillbox?stringtype=unspecified
    username: skillbox
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: true
  sql:
    init:
      mode: always
