server:
  port: 8086
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skillbox?stringtype=unspecified
    password: password
    username: skillbox
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: true
  sql:
    init:
      mode: never
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
jwt:
  token:
    secret: tyiuroiuopyiuioytidgfhdfqwerzxcqwer
    expired: 360000000
blacklist:
  deletionInterval: 1000