server:
  port: 8086

spring:
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5432/skillbox?stringtype=unspecified
    password: password
    username: skillbox
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    show-sql: false
  sql:
    init:
      mode: never
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

jwt:
  token:
    secret: tyiuroiuopyiuioytidgfhdfqwerzxcqwer
    expired: 360000000

blacklist:
  deletionInterval: 1000

mail-service:
  server-address: http://localhost:8086
  front-address: http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true

cloudinary:
  cloud_name: "zeroneproject"
  api_key: "551572451498292"
  api_secret: "bmOA13-uV_37Hm9Vfu4E_heObw4"

vk-api:
  access-token: a37d0c0ca37d0c0ca37d0c0c4aa06fe252aa37da37d0c0cc7793a5be33eac3846e483d9
  root-url: https://api.vk.com/method
  find-countries-method-uri: /database.getCountries
  find-cities-method-uri: /database.getCities
  version: 5.131


