server:
  port: 8086

spring:
  kafka:
    bootstrap-servers: localhost:9092
    kafka-topic: message-topic
  datasource:
    url: jdbc:postgresql://localhost:5432/skillbox?stringtype=unspecified
    password: password
    username: skillbox
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    show-sql: false
  sql:
    init:
      mode: never
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

#  data:
#    redis:
#      host: 0.0.0.0
#      database: 0
#      port: 6379
#      password: password123
#      timeout: 60000

jwt:
  token:
    secret: tyiuroiuopyiuioytidgfhdfqwerzxcqwer
    expired: 360000000

blacklist:
  deletionInterval: 1000

mail-service:
  server-address: http://localhost:8086
  front-address: http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true

cloudinary:
  cloud_name: "zeroneproject"
  api_key: "551572451498292"
  api_secret: "bmOA13-uV_37Hm9Vfu4E_heObw4"

vk-api:
  access-token: a37d0c0ca37d0c0ca37d0c0c4aa06fe252aa37da37d0c0cc7793a5be33eac3846e483d9
  root-url: https://api.vk.com/method
  find-countries-method-uri: /database.getCountries
  find-cities-method-uri: /database.getCities
  version: 5.131

google-drive:
  app_name: 'ZeroneSocialNetLogs'
  tokens_path: 'tokens'
  credentials_path: '/credentials.json'
  space: 'drive'
  fields: 'nextPageToken, files(id, name, createdTime, mimeType, size)'
  fields_set: 'id, name'
  file_type: 'text/log'
  access_type: 'offline'
  port: 8089
  authorize: 'user'
  index_of_first_element: 0
  months_to_subtract: 1
  mime_type: 'application/vnd.google-apps.folder'
  folder_name: logs

scheduled-tasks:
  google-drive-scanner: '0 0 3 15 * ?'
  vk-countries-uploader: '0 5 8 * * SUN'

log-settings:
  output-path: logs

websocket:
  host: 0.0.0.0
  port: 1111