server.port: 8086

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    show-sql: false
  sql:
    init:
      mode: never
  liquibase:
    enabled: true

socket-server:
  port: 1111
  host: localhost
