spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skillbox?stringtype=unspecified
    password: password
    username: skillbox
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc.lob.non_contextual_creation: true
    show-sql: true
  sql:
    init:
      mode: always
  liquibase:
    enabled: false