spring:
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/skillbox
    username: skillbox
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        jdbc.lob.non_contextual_creation: true
    show-sql: true
  sql:
    init:
      mode: always
#      platform: postgresql
