spring:
  jpa:
    show-sql: false
  liquibase:
    enabled: false
  kafka:
    bootstrap-servers: "kafka:9092"
  data:
    redis:
      host: redis
  datasource:
    url: jdbc:postgresql://postgres:5432/skillbox?stringtype=unspecified
    username: skillbox
    password: password

TZ: "Europe/Moscow"
EUREKA:
  CLIENT:
    SERVICE-URL:
      DEFAULTZONE: http://eureka-server:8761/eureka

mail-service:
  front-address: http://zerone-net.ru
