server:
  port: 8088

spring:
  application:
    name: zerone-backend
  kafka:
    bootstrap-servers: "0.0.0.0:29092"
  datasource:
    url: jdbc:postgresql://localhost:5432/skillbox?stringtype=unspecified
    password: ENC(+dNfPpTN2mOluglR/AsSUOBEDFQ+hLWB95yRV65Zn8EEhq23VZHxLzZ6JgbVlHLj)
    username: skillbox
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    show-sql: false
  sql:
    init:
      mode: never
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: 0.0.0.0
      database: 0
      port: 6379
      password: ENC(wJAAIHbtNA66iwW9zR5R1bY1Nnwo+sr2nSklkdJPikyY3SCxXanHtw4572Mv9j4h)
      timeout: 60000

jwt:
  token:
    secret: ENC(9jWZnwRnrWO4KzoYwZkbgScVRkefKOLGBYE6eZMvIxldd3Q9XpL4s2MkfniUCb9Cc6Dx8qNLLS78ZYqB84A0ovk+kQO+kbPRY+dUKxHC5LI=)
    expired: 360000000

blacklist:
  deletionInterval: 1000

mail-service:
  server-address: http://localhost:8086
  front-address: http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true

cloudinary:
  cloud_name: "zeroneproject"
  api_key: "551572451498292"
  api_secret: ENC(dgE0iZNQUsK+UvOkqHGMbulzmuJhwyFCdfC0LWqkYM7Eyt6VuaX/hDU2Q6ZJjq8b9bfsVtFc7A0YoU9e7YEV1g==)
  max_file_size: 10485760 # 10MB
  max_image_width: 5000
  max_image_height: 5000
  allowed_formats: ["jpg", "jpeg", "png", "gif"]
  unique_filename: true
  overwrite: false
  invalidate: true

vk-api:
  access-token: ENC(s8z3ziBwCQL3OkhvdDVox4trWeL0fVtkWMM70oPyfFgIMPpHZaiI4rK++2uy2+rWL5io2LX5bDG29GwDrvEWi0mg8FfCkJ10WK5tfnGD1dg9GGK69cEf26JM0qOeiPPHe7KKfvvt71I2OlbVYspWWQ==)
  root-url: https://api.vk.com/method
  find-countries-method-uri: /database.getCountries
  find-cities-method-uri: /database.getCities
  version: 5.131

google-drive:
  app_name: 'zerone-logs'
  tokens_path: 'tokens'
  credentials_path: '/credentials.json'
  space: 'drive'
  fields: 'nextPageToken, files(id, name, createdTime, mimeType, size)'
  fields_set: 'id, name'
  file_type: 'text/log'
  access_type: 'offline'
  port: 8089
  authorize: 'user'
  index_of_first_element: 0
  months_to_subtract: 1
  mime_type: 'application/vnd.google-apps.folder'
  folder_name: logs

scheduled-tasks:
  google-drive-scanner: '0 0 0 * * ?'
  vk-countries-uploader: '0 5 8 * * SUN'
  recommendation-creator: '0 0 2 * * ?'

log-settings:
  output-path: logs

websocket:
  host: 0.0.0.0
  port: 1111

kafka:
  kafka-topic: message-topic

springdoc:
  swagger-ui:
    path: /swagger

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

dadata:
  client:
    token: ENC(nlH2r4Liy7IlV6pI89cJ+0Z4vJB9gbDMu7WMBOLCHLGKS0lTFE7YtG91KkoIMpi7OARrXFNMOVh4SVOWn30g4ZP8SYqxxP5LW+SYjpHOeZk=)

ip-check:
  url: "http://checkip.amazonaws.com/"

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
