name: Migration job

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: liquibase-github-actions/update@v4.21.1
      with:
        changelogFile: ${{ secrets.DATABASE_CHANGELOG_PATH }}
        url: ${{ secrets.DATABASE_URL }}
        username: ${{ secrets.DATABASE_USERNAME }}
        password: ${{ secrets.DATABASE_PASSWORD }}
